### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by Iskizar** [Iskizar/Wiki-Games#5]
Анализ аналогов и прототипов
При проектировании сайта были взяты некоторые идеи и интересные дизайнерские подходы с других подобных сайтов.
Основные информационные разделы вики сайтов:
1.Раздел с играми
2.Разделы с игровыми составляющими

 - Интернет сайт FANDOM.com (https://www.fandom.com).
 
![image](https://user-images.githubusercontent.com/106599435/224952982-088bdfc2-1538-4f33-a66f-e5c598e2b161.png)
Рисунок 2.1 – Главная страница сайта FANDOM
![image](https://user-images.githubusercontent.com/106599435/224953075-d2c854ea-4d5a-4564-b61c-460831807bf3.png)

Рисунок 2.2 – Раздел с конкретной игрой на FANDOM

Взяты идеи:

1.  Ориентация на сайте посредством поиска и выбора нужного “Фандома” и дальнейшего перехода к конкретному разделу.
2. Создание заглавной страницы для каждой игры.
3. Изменение интерфейса в зависимости от раздела в игрой, в котором находится пользователь.

Недостатком является сильно перегруженный интерфейс и огромное количество новостей с различных “Фандомов”, что может запутать пользователя.  

-Интернет сайт Wikipedia.org (https://ru.wikipedia.org)
![image](https://user-images.githubusercontent.com/106599435/224953101-83216c4d-8b85-446f-8fa5-ecaab62185ef.png)

Рисунок 2.3 – Раздел с конкретной игрой на Wikipedia
Взята идея создания отдельных страниц с подробной информацией о каждом объекте.
Недостатком является отсутствие удобной навигации по связанным с игрой разделам, что может вызвать трудности у пользователя.

**Comment by wldmr-key** [comment]
норм. но не хватает выводов, что из аналогов ты берешь для своего приложения, а что отвергаешь

**Comment by wldmr-key** [comment]
норм
