### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by Iskizar** [Iskizar/Wiki-Games#7]
Обычно сайты имеют 3 основных блока: header, body(main), footer. В разработанном сайте имеются header и body. Блок header изменяется в зависимости от того, а разделе какой игры находится пользователь.
	В блоке header находятся основная навигация сайта, в котором расположены основны разделы игры, например: Главная, Локации, Оружие, Персонажи. Если пользователь не авторизован, то в правой части header будет расположена кнопка «Вход», при нажатии которой пользователь может либо войти на сайт с помощью логина и пароля, либо зарегистрироваться на сайте. Если пользователь авторизован, то вместо кнопки «Регистрация» будет располагаться строка с именем пользователя, а вместо кнопки «Войти» будет кнопка «Выйти». Поле «Выйти» отвечает за выход пользователя из учётной записи.
![image](https://user-images.githubusercontent.com/106599435/226183496-0cb75e25-9740-4258-b51b-784cb76b5f11.png)
Рисунок 3.1 – Header сайта

В блоке main находится основной контент сайт, который отличается в каждой странице. Ниже приведены основные страницы, в которых пользователь может взаимодействовать, и их содержание:

«Главная»: расположены ссылки на игры, “Hollow Knight” и “Dead Cells”, написана общая информация о сайте.
![image](https://user-images.githubusercontent.com/106599435/226183518-1aa78b30-ca84-4d3a-a222-1fad386ccca4.png)

Рисунок 3.2 – Главная страница

«Hollow Knight»: расположены ссылки на разделы, “Главная”, “Локации”,
“Оружие”, “Персонажи”, написана общая информация о игре.

![image](https://user-images.githubusercontent.com/106599435/226183526-51eeada1-65f9-459a-b8ee-e3797fbd60a5.png)

Рисунок 3.3 – Главная страница «Hollow Knight»

«Персонажи»: расположен список всех персонажей, показана общая информация о каждом персонаже. Каждую статью можно прочитать более подробно.
![image](https://user-images.githubusercontent.com/106599435/226183531-a5dc6be0-1e17-4228-b548-2f48c703ba6b.png)

Рисунок 3.4 – Страница «Персонажи»
«Читать детально»: выводится подробная информация о персонаже. В нижней части статьи находятся кнопки для редактирования или удаления статьи.
![image](https://user-images.githubusercontent.com/106599435/226183544-e7ce032c-846c-4d92-91c4-7f9f069952de.png)

Рисунок 3.5 – Страница «Читать детально»

«Редактировать»: Выводится форма для редактирования статьи.

![image](https://user-images.githubusercontent.com/106599435/226183549-da3bc9ac-9546-44ab-807e-c7d15504bb6d.png)

Рисунок 3.6 – Страница «Редактировать»

Внизу списка статей расположена кнопка «Добавить запись».
 
![image](https://user-images.githubusercontent.com/106599435/226183553-32ae18b5-d3c8-4123-90e9-0549e0a04074.png)

Рисунок 3.7 – Нижняя часть страницы “Персонажи”

«Добавить запись»: Выводится форма для добавления статьи.

![image](https://user-images.githubusercontent.com/106599435/226183566-54057b60-161e-4c3d-8979-ee17f0c422d9.png)

Рисунок 3.8 – Страница “Добавить запись”

**Comment by wldmr-key** [comment]
как скетчи пойдет. Как текст РПЗ нуждается в оформлении

**Comment by Iskizar** [comment]
Как я понял, нужно описать элементы пользовательского интерфейса, верно? Я исправил, но если я неправильно понял, можете, пожалуйста, объяснить, что я не так делаю?

**Comment by wldmr-key** [comment]
все правильно сделал
